// Système de traduction global pour tout le site
export interface Language {
  code: string;
  name: string;
  flag: string;
}

export const supportedLanguages: Language[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
];

// Traductions globales pour tout le site
export const globalTranslations = {
  en: {
    pricingTitle: "Choose your plan",
    pricingSubtitle: "Unlock premium trading signals and improve your strategy.",
    buyWithStripe: "Buy with Stripe",
    buyWithLabel: "Or pay with crypto",
    cryptoInstantTagline: "Instant crypto payment",
    cryptoPayCta: "Pay",
    payWithCrypto: "Pay with crypto",
    // Contenu principal
    heroTitle: "AI-POWERED REAL-TIME TRADING SIGNALS",
    heroSubtitle: "AND OUR PROFESSIONAL TRADERS",
    heroDescription: "Harness the power of our advanced AI to get institutional-grade BUY/SELL signals for Forex, Indices, and Crypto markets.",
    activeTraders: "active traders online",
    
    // Boutons et actions
    signIn: "Sign In",
    signUp: "Sign Up",
    getStarted: "Get Started",
    upgradeNow: "Upgrade Now",
    learnMore: "Learn More",
    
    // Section d'affiliation
    affiliateTitle: "Join our affiliate program",
    affiliateDescription: "Earn 35% commission on each registration generated via your unique links.",
    affiliateButton: "Join the program",
    affiliateLink: "Click here to join the affiliate program",
    affiliateStats: "COMMISSIONS PAID",
    affiliateEmail: "realtimetradingsignal@gmail.com",
    
    // Trading Bot Settings
    tradingBotSettings: "Trading Bot Settings",
    configureTradingSettings: "Configure your trading settings",
    category: "Category",
    asset: "Asset",
    timeframe: "Timeframe",
    open: "Open",
    closed: "Closed",
    logInToGetSignals: "Log In to Get Signals",
    
    // Active Signals
    activeSignals: "ACTIVE SIGNALS",
    noActiveSignals: "No active signals.",
    selectSettingsFirst: "First select settings, then click on Start Signals, and you will see the active signal here.",
    startSignals: "Start Signals",
    
    // Footer
    footerDescription: "Real-time trading signals generated by AI and our professional traders",
    services: "Services",
    forexSignals: "Forex Signals",
    cryptoSignals: "Crypto Signals",
    indicesSignals: "Indices Signals",
    technicalAnalysis: "Technical Analysis",
    support: "Support",
    customerService: "Customer Service",
    becomeAffiliate: "Become an Affiliate",
    faq: "FAQ",
    legal: "Legal",
    termsConditions: "Terms & Conditions",
    privacyPolicy: "Privacy Policy",
    tradingRisks: "Trading Risks",
    legalNotice: "Legal Notice",
    copyright: "© 2025 Real-time Trading Signals. All rights reserved."
  },
  fr: {
    pricingTitle: "Choisissez votre plan",
    pricingSubtitle: "Débloquez des signaux premium et optimisez votre stratégie.",
    buyWithStripe: "Acheter avec Stripe",
    buyWithLabel: "Ou payez en crypto",
    cryptoInstantTagline: "Paiement crypto instantané",
    cryptoPayCta: "Payer",
    payWithCrypto: "Payer avec cryptos",
    // Contenu principal
    heroTitle: "SIGNAUX DE TRADING EN TEMPS RÉEL ALIMENTÉS PAR IA",
    heroSubtitle: "ET NOS TRADERS PROFESSIONNELS",
    heroDescription: "Exploitez la puissance de notre IA avancée pour obtenir des signaux ACHETER/VENDRE de niveau institutionnel pour les marchés Forex, Indices et Crypto.",
    activeTraders: "traders actifs en ligne",
    
    // Boutons et actions
    signIn: "Se connecter",
    signUp: "S'inscrire",
    getStarted: "Commencer",
    upgradeNow: "Mettre à niveau maintenant",
    learnMore: "En savoir plus",
    
    // Section d'affiliation
    affiliateTitle: "Rejoignez notre programme d'affiliation",
    affiliateDescription: "Gagnez 35% de commission sur chaque inscription générée via vos liens uniques.",
    affiliateButton: "Rejoindre le programme",
    affiliateLink: "Cliquez ici pour rejoindre le programme d'affiliation",
    affiliateStats: "COMMISSIONS PAYÉES",
    affiliateEmail: "realtimetradingsignal@gmail.com",
    
    // Trading Bot Settings
    tradingBotSettings: "Paramètres du Bot de Trading",
    configureTradingSettings: "Configurez vos paramètres de trading",
    category: "Catégorie",
    asset: "Actif",
    timeframe: "Période",
    open: "Ouvert",
    closed: "Fermé",
    logInToGetSignals: "Se connecter pour obtenir les signaux",
    
    // Active Signals
    activeSignals: "SIGNAUX ACTIFS",
    noActiveSignals: "Aucun signal actif.",
    selectSettingsFirst: "Sélectionnez d'abord les paramètres, puis cliquez sur Démarrer les signaux, et vous verrez le signal actif ici.",
    startSignals: "Démarrer les signaux",
    
    // Footer
    footerDescription: "Signaux de trading en temps réel générés par l'IA et nos traders professionnels",
    services: "Services",
    forexSignals: "Signaux Forex",
    cryptoSignals: "Signaux Crypto",
    indicesSignals: "Signaux Indices",
    technicalAnalysis: "Analyse Technique",
    support: "Support",
    customerService: "Service Client",
    becomeAffiliate: "Devenir Affilié",
    faq: "FAQ",
    legal: "Légal",
    termsConditions: "Conditions Générales",
    privacyPolicy: "Politique de Confidentialité",
    tradingRisks: "Risques de Trading",
    legalNotice: "Mentions Légales",
    copyright: "© 2025 Signaux de Trading en Temps Réel. Tous droits réservés."
  },
  es: {
    pricingTitle: "Elige tu plan",
    pricingSubtitle: "Desbloquea señales premium y mejora tu estrategia.",
    buyWithStripe: "Comprar con Stripe",
    buyWithLabel: "O paga con crypto",
    cryptoInstantTagline: "Pago cripto instantáneo",
    cryptoPayCta: "Pagar",
    payWithCrypto: "Pagar con criptos",
    // Contenu principal
    heroTitle: "SEÑALES DE TRADING EN TIEMPO REAL IMPULSADAS POR IA",
    heroSubtitle: "Y NUESTROS TRADERS PROFESIONALES",
    heroDescription: "Aprovecha el poder de nuestra IA avanzada para obtener señales COMPRAR/VENDER de nivel institucional para mercados Forex, Índices y Crypto.",
    activeTraders: "traders activos en línea",
    
    // Boutons et actions
    signIn: "Iniciar sesión",
    signUp: "Registrarse",
    getStarted: "Comenzar",
    upgradeNow: "Actualizar ahora",
    learnMore: "Saber más",
    
    // Section d'affiliation
    affiliateTitle: "Únete a nuestro programa de afiliados",
    affiliateDescription: "Gana 35% de comisión en cada registro generado a través de tus enlaces únicos.",
    affiliateButton: "Únete al programa",
    affiliateLink: "Haz clic aquí para unirte al programa de afiliados",
    affiliateStats: "COMISIONES PAGADAS",
    affiliateEmail: "realtimetradingsignal@gmail.com",
    
    // Trading Bot Settings
    tradingBotSettings: "Configuración del Bot de Trading",
    configureTradingSettings: "Configura tus parámetros de trading",
    category: "Categoría",
    asset: "Activo",
    timeframe: "Marco temporal",
    open: "Abierto",
    closed: "Cerrado",
    logInToGetSignals: "Iniciar sesión para obtener señales",
    
    // Active Signals
    activeSignals: "SEÑALES ACTIVAS",
    noActiveSignals: "No hay señales activas.",
    selectSettingsFirst: "Primero selecciona la configuración, luego haz clic en Iniciar Señales, y verás la señal activa aquí.",
    startSignals: "Iniciar Señales",
    
    // Footer
    footerDescription: "Señales de trading en tiempo real generadas por IA y nuestros traders profesionales",
    services: "Servicios",
    forexSignals: "Señales Forex",
    cryptoSignals: "Señales Crypto",
    indicesSignals: "Señales Índices",
    technicalAnalysis: "Análisis Técnico",
    support: "Soporte",
    customerService: "Servicio al Cliente",
    becomeAffiliate: "Convertirse en Afiliado",
    faq: "FAQ",
    legal: "Legal",
    termsConditions: "Términos y Condiciones",
    privacyPolicy: "Política de Privacidad",
    tradingRisks: "Riesgos de Trading",
    legalNotice: "Aviso Legal",
    copyright: "© 2025 Señales de Trading en Tiempo Real. Todos los derechos reservados."
  },
  it: {
    pricingTitle: "Scegli il tuo piano",
    pricingSubtitle: "Sblocca segnali premium e migliora la tua strategia.",
    buyWithStripe: "Acquista con Stripe",
    buyWithLabel: "Oppure paga in cripto",
    cryptoInstantTagline: "Pagamento cripto istantaneo",
    cryptoPayCta: "Paga",
    payWithCrypto: "Paga con cripto",
    // Contenu principal
    heroTitle: "SEGNALI DI TRADING IN TEMPO REALE ALIMENTATI DA IA",
    heroSubtitle: "E I NOSTRI TRADER PROFESSIONISTI",
    heroDescription: "Sfrutta il potere della nostra IA avanzata per ottenere segnali COMPRA/VENDI di livello istituzionale per i mercati Forex, Indici e Crypto.",
    activeTraders: "trader attivi online",
    
    // Boutons et actions
    signIn: "Accedi",
    signUp: "Registrati",
    getStarted: "Inizia",
    upgradeNow: "Aggiorna ora",
    learnMore: "Scopri di più",
    
    // Section d'affiliation
    affiliateTitle: "Unisciti al nostro programma di affiliazione",
    affiliateDescription: "Guadagna il 35% di commissione su ogni registrazione generata tramite i tuoi link unici.",
    affiliateButton: "Unisciti al programma",
    affiliateLink: "Clicca qui per unirti al programma di affiliazione",
    affiliateStats: "COMMISSIONI PAGATE",
    affiliateEmail: "realtimetradingsignal@gmail.com",
    
    // Trading Bot Settings
    tradingBotSettings: "Impostazioni Bot di Trading",
    configureTradingSettings: "Configura le tue impostazioni di trading",
    category: "Categoria",
    asset: "Attivo",
    timeframe: "Timeframe",
    open: "Aperto",
    closed: "Chiuso",
    logInToGetSignals: "Accedi per ottenere i segnali",
    
    // Active Signals
    activeSignals: "SEGNALI ATTIVI",
    noActiveSignals: "Nessun segnale attivo.",
    selectSettingsFirst: "Prima seleziona le impostazioni, poi clicca su Inizia Segnali, e vedrai il segnale attivo qui.",
    startSignals: "Inizia Segnali",
    
    // Footer
    footerDescription: "Segnali di trading in tempo reale generati da IA e dai nostri trader professionisti",
    services: "Servizi",
    forexSignals: "Segnali Forex",
    cryptoSignals: "Segnali Crypto",
    indicesSignals: "Segnali Indici",
    technicalAnalysis: "Analisi Tecnica",
    support: "Supporto",
    customerService: "Servizio Clienti",
    becomeAffiliate: "Diventa Affiliato",
    faq: "FAQ",
    legal: "Legale",
    termsConditions: "Termini e Condizioni",
    privacyPolicy: "Informativa sulla Privacy",
    tradingRisks: "Rischi di Trading",
    legalNotice: "Note Legali",
    copyright: "© 2025 Segnali di Trading in Tempo Reale. Tutti i diritti riservati."
  },
  pt: {
    pricingTitle: "Escolha seu plano",
    pricingSubtitle: "Desbloqueie sinais premium e melhore sua estratégia.",
    buyWithStripe: "Comprar com Stripe",
    buyWithLabel: "Ou pague com cripto",
    cryptoInstantTagline: "Pagamento cripto instantâneo",
    cryptoPayCta: "Pagar",
    payWithCrypto: "Pagar com criptos",
    // Contenu principal
    heroTitle: "SINAIS DE TRADING EM TEMPO REAL ALIMENTADOS POR IA",
    heroSubtitle: "E NOSSOS TRADERS PROFISSIONAIS",
    heroDescription: "Aproveite o poder da nossa IA avançada para obter sinais COMPRAR/VENDER de nível institucional para mercados Forex, Índices e Crypto.",
    activeTraders: "traders ativos online",
    
    // Boutons et actions
    signIn: "Entrar",
    signUp: "Registrar",
    getStarted: "Começar",
    upgradeNow: "Atualizar agora",
    learnMore: "Saber mais",
    
    // Section d'affiliation
    affiliateTitle: "Junte-se ao nosso programa de afiliados",
    affiliateDescription: "Ganhe 35% de comissão em cada registro gerado através dos seus links únicos.",
    affiliateButton: "Juntar-se ao programa",
    affiliateLink: "Clique aqui para se juntar ao programa de afiliados",
    affiliateStats: "COMISSÕES PAGAS",
    affiliateEmail: "realtimetradingsignal@gmail.com",
    
    // Trading Bot Settings
    tradingBotSettings: "Configurações do Bot de Trading",
    configureTradingSettings: "Configure suas configurações de trading",
    category: "Categoria",
    asset: "Ativo",
    timeframe: "Timeframe",
    open: "Aberto",
    closed: "Fechado",
    logInToGetSignals: "Entrar para obter sinais",
    
    // Active Signals
    activeSignals: "SINAIS ATIVOS",
    noActiveSignals: "Nenhum sinal ativo.",
    selectSettingsFirst: "Primeiro selecione as configurações, depois clique em Iniciar Sinais, e você verá o sinal ativo aqui.",
    startSignals: "Iniciar Sinais"
  },
  ru: {
    pricingTitle: "Выберите тариф",
    pricingSubtitle: "Получайте премиальные сигналы и улучшайте стратегию.",
    buyWithStripe: "Оплатить через Stripe",
    buyWithLabel: "Или оплатите криптовалютой",
    cryptoInstantTagline: "Мгновенный крипто-платеж",
    cryptoPayCta: "Оплатить",
    payWithCrypto: "Оплатить криптовалютой",
    // Contenu principal
    heroTitle: "СИГНАЛЫ ТОРГОВЛИ В РЕАЛЬНОМ ВРЕМЕНИ НА ОСНОВЕ ИИ",
    heroSubtitle: "И НАШИ ПРОФЕССИОНАЛЬНЫЕ ТРЕЙДЕРЫ",
    heroDescription: "Используйте силу нашего продвинутого ИИ для получения институциональных сигналов ПОКУПАТЬ/ПРОДАВАТЬ для рынков Forex, Индексов и Крипто.",
    activeTraders: "активных трейдеров онлайн",
    
    // Boutons et actions
    signIn: "Войти",
    signUp: "Зарегистрироваться",
    getStarted: "Начать",
    upgradeNow: "Обновить сейчас",
    learnMore: "Узнать больше",
    
    // Section d'affiliation
    affiliateTitle: "Присоединяйтесь к нашей партнерской программе",
    affiliateDescription: "Зарабатывайте 35% комиссии с каждой регистрации, сгенерированной через ваши уникальные ссылки.",
    affiliateButton: "Присоединиться к программе",
    affiliateLink: "Нажмите здесь, чтобы присоединиться к партнерской программе",
    affiliateStats: "ВЫПЛАЧЕННЫЕ КОМИССИИ",
    affiliateEmail: "realtimetradingsignal@gmail.com",
    
    // Trading Bot Settings
    tradingBotSettings: "Настройки Торгового Бота",
    configureTradingSettings: "Настройте параметры торговли",
    category: "Категория",
    asset: "Актив",
    timeframe: "Временной интервал",
    open: "Открыто",
    closed: "Закрыто",
    logInToGetSignals: "Войти для получения сигналов",
    
    // Active Signals
    activeSignals: "АКТИВНЫЕ СИГНАЛЫ",
    noActiveSignals: "Нет активных сигналов.",
    selectSettingsFirst: "Сначала выберите настройки, затем нажмите Начать Сигналы, и вы увидите активный сигнал здесь.",
    startSignals: "Начать Сигналы"
  },
  ar: {
    pricingTitle: "اختر خطتك",
    pricingSubtitle: "افتح إشارات مميزة وحسّن استراتيجيتك.",
    buyWithStripe: "اشترِ عبر Stripe",
    buyWithLabel: "أو ادفع بالعملات المشفرة",
    cryptoInstantTagline: "دفع فوري بالعملات المشفرة",
    cryptoPayCta: "ادفع",
    payWithCrypto: "ادفع بالعملات المشفرة",
    // Contenu principal
    heroTitle: "إشارات التداول في الوقت الفعلي مدعومة بالذكاء الاصطناعي",
    heroSubtitle: "وتجارنا المحترفون",
    heroDescription: "استفد من قوة الذكاء الاصطناعي المتقدم للحصول على إشارات شراء/بيع على مستوى المؤسسات لأسواق الفوركس والمؤشرات والعملات المشفرة.",
    activeTraders: "تاجر نشط على الإنترنت",
    
    // Boutons et actions
    signIn: "تسجيل الدخول",
    signUp: "التسجيل",
    getStarted: "ابدأ",
    upgradeNow: "ترقية الآن",
    learnMore: "اعرف المزيد",
    
    // Section d'affiliation
    affiliateTitle: "انضم إلى برنامج الشراكة الخاص بنا",
    affiliateDescription: "اكسب 35% عمولة على كل تسجيل يتم إنشاؤه عبر روابطك الفريدة.",
    affiliateButton: "انضم إلى البرنامج",
    affiliateLink: "انقر هنا للانضمام إلى برنامج الشراكة",
    affiliateStats: "العمولات المدفوعة",
    affiliateEmail: "realtimetradingsignal@gmail.com",
    
    // Trading Bot Settings
    tradingBotSettings: "إعدادات بوت التداول",
    configureTradingSettings: "قم بتكوين إعدادات التداول الخاصة بك",
    category: "الفئة",
    asset: "الأصل",
    timeframe: "الإطار الزمني",
    open: "مفتوح",
    closed: "مغلق",
    logInToGetSignals: "تسجيل الدخول للحصول على الإشارات",
    
    // Active Signals
    activeSignals: "الإشارات النشطة",
    noActiveSignals: "لا توجد إشارات نشطة.",
    selectSettingsFirst: "أولاً اختر الإعدادات، ثم انقر على بدء الإشارات، وسترى الإشارة النشطة هنا.",
    startSignals: "بدء الإشارات"
  },
  hi: {
    pricingTitle: "अपनी योजना चुनें",
    pricingSubtitle: "प्रीमियम सिग्नल अनलॉक करें और अपनी रणनीति सुधारें।",
    buyWithStripe: "Stripe से खरीदें",
    buyWithLabel: "या क्रिप्टो से भुगतान करें",
    cryptoInstantTagline: "तुरंत क्रिप्टो भुगतान",
    cryptoPayCta: "भुगतान करें",
    payWithCrypto: "क्रिप्टो से भुगतान करें",
    // Contenu principal
    heroTitle: "AI-संचालित रियल-टाइम ट्रेडिंग सिग्नल",
    heroSubtitle: "और हमारे पेशेवर ट्रेडर",
    heroDescription: "फॉरेक्स, इंडेक्स और क्रिप्टो बाजारों के लिए संस्थागत-ग्रेड खरीद/बेच सिग्नल प्राप्त करने के लिए हमारी उन्नत AI की शक्ति का उपयोग करें।",
    activeTraders: "सक्रिय ट्रेडर ऑनलाइन",
    
    // Boutons et actions
    signIn: "साइन इन",
    signUp: "साइन अप",
    getStarted: "शुरू करें",
    upgradeNow: "अभी अपग्रेड करें",
    learnMore: "और जानें",
    
    // Section d'affiliation
    affiliateTitle: "हमारे सहयोग कार्यक्रम में शामिल हों",
    affiliateDescription: "आपके अद्वितीय लिंक के माध्यम से उत्पन्न प्रत्येक पंजीकरण पर 35% कमीशन कमाएं।",
    affiliateButton: "कार्यक्रम में शामिल हों",
    affiliateLink: "सहयोग कार्यक्रम में शामिल होने के लिए यहां क्लिक करें",
    affiliateStats: "भुगतान किए गए कमीशन",
    affiliateEmail: "realtimetradingsignal@gmail.com",
    
    // Trading Bot Settings
    tradingBotSettings: "ट्रेडिंग बॉट सेटिंग्स",
    configureTradingSettings: "अपनी ट्रेडिंग सेटिंग्स कॉन्फ़िगर करें",
    category: "श्रेणी",
    asset: "संपत्ति",
    timeframe: "समय सीमा",
    open: "खुला",
    closed: "बंद",
    logInToGetSignals: "सिग्नल प्राप्त करने के लिए लॉग इन करें",
    
    // Active Signals
    activeSignals: "सक्रिय सिग्नल",
    noActiveSignals: "कोई सक्रिय सिग्नल नहीं।",
    selectSettingsFirst: "पहले सेटिंग्स चुनें, फिर स्टार्ट सिग्नल पर क्लिक करें, और आप यहां सक्रिय सिग्नल देखेंगे।",
    startSignals: "सिग्नल शुरू करें"
  }
};

// Fonction pour détecter la langue du navigateur
export const detectBrowserLanguage = (): string => {
  if (typeof window === 'undefined') return 'en';
  
  const browserLang = navigator.language || navigator.languages?.[0] || 'en';
  const langCode = browserLang.split('-')[0];
  
  // Vérifier si la langue est supportée
  const isSupported = supportedLanguages.some(lang => lang.code === langCode);
  return isSupported ? langCode : 'en';
};

// Fonction pour obtenir les traductions
export const getTranslations = (language: string) => {
  return globalTranslations[language as keyof typeof globalTranslations] || globalTranslations.en;
};