// Système de traduction global pour tout le site
export interface Language {
  code: string;
  name: string;
  flag: string;
}

export const supportedLanguages: Language[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
];

// Traductions globales pour tout le site
export const globalTranslations = {
  en: {
    pricingTitle: "Choose your plan",
    pricingSubtitle: "Unlock premium trading signals and improve your strategy.",
    buyWithStripe: "Buy with Stripe",
    buyWithLabel: "Or pay with crypto",
    cryptoInstantTagline: "Instant crypto payment",
    cryptoPayCta: "SELECT",
    payWithCrypto: "Cryptocurrency Payment",
    cryptoPaymentSubtext: "BTC, ETH, USDT & 150+ more",
    // Contenu principal
    heroTitle: "AI-POWERED REAL-TIME TRADING SIGNALS",
    heroSubtitle: "AND OUR PROFESSIONAL TRADERS",
    heroDescription: "Harness the power of our advanced AI to get institutional-grade BUY/SELL signals for Forex, Indices, and Crypto markets.",
    activeTraders: "active traders online",
    
    // Boutons et actions
    signIn: "Sign In",
    signUp: "Sign Up",
    getStarted: "Get Started",
    upgradeNow: "Upgrade Now",
    learnMore: "Learn More",
    
    // Section d'affiliation
    affiliateTitle: "Join our affiliate program",
    affiliateDescription: "Earn 35% commission on each registration generated via your unique links.",
    affiliateButton: "Join the program",
    affiliateLink: "Click here to join the affiliate program",
    affiliateStats: "COMMISSIONS PAID",
    affiliateEmail: "realtimetradingsignal@gmail.com",
    
    // Trading Bot Settings
    tradingBotSettings: "Trading Bot Settings",
    configureTradingSettings: "Configure your trading settings",
    category: "Category",
    asset: "Asset",
    timeframe: "Timeframe",
    open: "Open",
    closed: "Closed",
    logInToGetSignals: "Log In to Get Signals",
    tutorialVideoTitle: "How to Use Real-time Trading Signals Platform?",
    tutorialVideoSubtitle: "Watch our comprehensive tutorial guide",
    
    // Active Signals
    activeSignals: "ACTIVE SIGNALS",
    noActiveSignals: "No active signals.",
    selectSettingsFirst: "First select settings, then click on Start Signals, and you will see the active signal here.",
    startSignals: "Start Signals",
    
    // Signal Notifications
    signalGenerated: "Signal generated",
    signalGeneratedDescription: "New {type} signal generated for {asset} based on real-time technical analysis",
    signalActivated: "Signal Activated!",
    signalActivatedInfo: "A new {type} signal for {asset} has been generated from real-time market analysis.",
    signalExpired: "Signal expired",
    signalExpiredDescription: "The active signal has expired. You can now generate a new signal.",
    signalExpiredTitle: "Signal Expired",
    signalExpiredDismiss: "Click to dismiss",
    
    // Version
    versionName: "Version 2.0 - Real-Time Precision Edition",
    
    // Footer
    footerDescription: "Real-time trading signals generated by AI and our professional traders",
    services: "Services",
    forexSignals: "Forex Signals",
    cryptoSignals: "Crypto Signals",
    indicesSignals: "Indices Signals",
    technicalAnalysis: "Technical Analysis",
    support: "Support",
    customerService: "Customer Service",
    becomeAffiliate: "Become an Affiliate",
    faq: "FAQ",
    
    // User Menu
    homePage: "Home Page",
    profileSettings: "Profile & Settings",
    cancelSubscription: "Cancel Subscription",
    manageSubscription: "Manage Subscription",
    changePassword: "Change Password",
    suspendAccount: "Suspend Account",
    deleteAccount: "Delete Account",
    logOut: "Log out",
    
    // Cancel Subscription Modal
    cancelSubscriptionConfirm: "Are you sure you want to cancel your subscription? This action will stop your recurring billing.",
    beforeYouCancel: "Before you cancel:",
    cancelWarning1: "You'll lose access to premium trading signals",
    cancelWarning2: "Your subscription will end at the current billing period",
    cancelWarning3: "You can resubscribe anytime",
    cancelWarning4: "No refunds for the current billing period",
    cancelRedirectMessage: "You will be redirected to Stripe's secure portal to safely cancel your subscription.",
    keepSubscription: "Keep Subscription",
    
    // Change Password Modal
    changePasswordDescription: "Enter your current password and choose a new password",
    currentPassword: "Current Password",
    currentPasswordPlaceholder: "Enter your current password",
    newPassword: "New Password",
    newPasswordPlaceholder: "Enter your new password",
    confirmNewPassword: "Confirm New Password",
    confirmNewPasswordPlaceholder: "Confirm your new password",
    updatePassword: "Update Password",
    cancel: "Cancel",
    passwordUpdated: "Password Updated",
    passwordUpdatedDescription: "Your password has been successfully changed.",
    
    // Cookie Banner
    cookieBannerTitle: "We use cookies",
    cookieBannerDescription: "We use essential cookies for site functionality and analytics cookies to improve your experience. You can customize your preferences.",
    cookieAcceptAll: "Accept All",
    cookieRejectAll: "Reject All",
    cookieSettings: "Settings",
    cookieNecessary: "Necessary Cookies",
    cookieNecessaryDescription: "These cookies are essential for the website to function properly. They cannot be disabled.",
    cookieAnalytics: "Analytics Cookies",
    cookieAnalyticsDescription: "These cookies help us understand how visitors interact with our website by collecting and reporting information anonymously.",
    cookieSettingsTitle: "Cookie Settings",
    cookieSettingsDescription: "Customize your cookie preferences. You can enable or disable different types of cookies below.",
    cookieSavePreferences: "Save Preferences",
    legal: "Legal",
    termsConditions: "Terms & Conditions",
    privacyPolicy: "Privacy Policy",
    tradingRisks: "Trading Risks",
    legalNotice: "Legal Notice",
    copyright: "© 2025 Real-time Trading Signals. All rights reserved.",
    
    // Sub-header banner
    bannerBadge: "The Most Revolutionary Platform",
    bannerTitle: "Market Signals24",
    bannerDescription: "The first signal platform with triple validation: Artificial Intelligence + Human Experts + Market Confirmation. Zero tolerance for false signals.",
    bannerCta: "Discover Now",
    
    // Above-footer promo
    promoTitle: "Why Traders Choose Market Signals24?",
    promoSubtitle: "Join thousands of traders who already profit from our triple-validated signals",
    promoStat1Title: "Triple Validation",
    promoStat1Desc: "Every signal passes through AI, expert traders, and market confirmation before reaching you",
    promoStat2Title: "97.2% Accuracy",
    promoStat2Desc: "Our AI eliminates false signals — only the most reliable opportunities reach your screen",
    promoStat3Title: "24/7 Real-Time",
    promoStat3Desc: "Never miss an opportunity — our system monitors markets around the clock for you",
    promoCta: "Start Trading Smarter Today",
    promoUrgency: "Limited spots available — Premium access may close soon",
    
    // Popup
    popupTitle: "Don't Trade Blind!",
    popupSubtitle: "93% of traders lose money using unverified signals.",
    popupHighlight: "Market Signals24 is the ONLY platform that triple-validates every signal before sending it to you.",
    popupBullet1: "AI analyzes 10,000+ data points per second",
    popupBullet2: "Expert traders confirm every signal manually",
    popupBullet3: "Market conditions verified in real-time",
    popupCta: "Get Verified Signals Now",
    popupDismiss: "I'll risk trading without verification"
  },
  fr: {
    pricingTitle: "Choisissez votre plan",
    pricingSubtitle: "Débloquez des signaux premium et optimisez votre stratégie.",
    buyWithStripe: "Acheter avec Stripe",
    buyWithLabel: "Ou payez en crypto",
    cryptoInstantTagline: "Paiement crypto instantané",
    cryptoPayCta: "CHOISIR",
    payWithCrypto: "Paiement Cryptomonnaie",
    cryptoPaymentSubtext: "BTC, ETH, USDT et plus de 150 cryptos",
    // Contenu principal
    heroTitle: "SIGNAUX DE TRADING EN TEMPS RÉEL ALIMENTÉS PAR IA",
    heroSubtitle: "ET NOS TRADERS PROFESSIONNELS",
    heroDescription: "Exploitez la puissance de notre IA avancée pour obtenir des signaux ACHETER/VENDRE de niveau institutionnel pour les marchés Forex, Indices et Crypto.",
    activeTraders: "traders actifs en ligne",
    
    // Boutons et actions
    signIn: "Se connecter",
    signUp: "S'inscrire",
    getStarted: "Commencer",
    upgradeNow: "Mettre à niveau maintenant",
    learnMore: "En savoir plus",
    
    // Section d'affiliation
    affiliateTitle: "Rejoignez notre programme d'affiliation",
    affiliateDescription: "Gagnez 35% de commission sur chaque inscription générée via vos liens uniques.",
    affiliateButton: "Rejoindre le programme",
    affiliateLink: "Cliquez ici pour rejoindre le programme d'affiliation",
    affiliateStats: "COMMISSIONS PAYÉES",
    affiliateEmail: "realtimetradingsignal@gmail.com",
    
    // Trading Bot Settings
    tradingBotSettings: "Paramètres du Bot de Trading",
    configureTradingSettings: "Configurez vos paramètres de trading",
    category: "Catégorie",
    asset: "Actif",
    timeframe: "Période",
    open: "Ouvert",
    closed: "Fermé",
    logInToGetSignals: "Se connecter pour obtenir les signaux",
    tutorialVideoTitle: "Comment utiliser la plateforme de signaux de trading en temps réel ?",
    tutorialVideoSubtitle: "Regardez notre guide de tutoriel complet",
    
    // Active Signals
    activeSignals: "SIGNAUX ACTIFS",
    noActiveSignals: "Aucun signal actif.",
    selectSettingsFirst: "Sélectionnez d'abord les paramètres, puis cliquez sur Démarrer les signaux, et vous verrez le signal actif ici.",
    startSignals: "Démarrer les signaux",
    
    // Signal Notifications
    signalGenerated: "Signal généré",
    signalGeneratedDescription: "Nouveau signal {type} généré pour {asset} basé sur l'analyse technique en temps réel",
    signalActivated: "Signal activé !",
    signalActivatedInfo: "Un nouveau signal {type} pour {asset} a été généré à partir de l'analyse de marché en temps réel.",
    signalExpired: "Signal expiré",
    signalExpiredDescription: "Le signal actif a expiré. Vous pouvez maintenant générer un nouveau signal.",
    signalExpiredTitle: "Signal Expiré",
    signalExpiredDismiss: "Cliquez pour fermer",
    
    // Version
    versionName: "Version 2.0 - Real-Time Precision Edition",
    
    // Footer
    footerDescription: "Signaux de trading en temps réel générés par l'IA et nos traders professionnels",
    services: "Services",
    forexSignals: "Signaux Forex",
    cryptoSignals: "Signaux Crypto",
    indicesSignals: "Signaux Indices",
    technicalAnalysis: "Analyse Technique",
    support: "Support",
    customerService: "Service Client",
    becomeAffiliate: "Devenir Affilié",
    faq: "FAQ",
    
    // User Menu
    homePage: "Page d'accueil",
    profileSettings: "Profil et Paramètres",
    cancelSubscription: "Annuler l'abonnement",
    manageSubscription: "Gérer l'abonnement",
    changePassword: "Changer le mot de passe",
    suspendAccount: "Suspendre le compte",
    deleteAccount: "Supprimer le compte",
    logOut: "Se déconnecter",
    
    // Cancel Subscription Modal
    cancelSubscriptionConfirm: "Êtes-vous sûr de vouloir annuler votre abonnement ? Cette action arrêtera votre facturation récurrente.",
    beforeYouCancel: "Avant d'annuler :",
    cancelWarning1: "Vous perdrez l'accès aux signaux de trading premium",
    cancelWarning2: "Votre abonnement se terminera à la période de facturation actuelle",
    cancelWarning3: "Vous pouvez vous réabonner à tout moment",
    cancelWarning4: "Aucun remboursement pour la période de facturation actuelle",
    cancelRedirectMessage: "Vous serez redirigé vers le portail sécurisé de Stripe pour annuler votre abonnement en toute sécurité.",
    keepSubscription: "Conserver l'abonnement",
    
    // Change Password Modal
    changePasswordDescription: "Entrez votre mot de passe actuel et choisissez un nouveau mot de passe",
    currentPassword: "Mot de passe actuel",
    currentPasswordPlaceholder: "Entrez votre mot de passe actuel",
    newPassword: "Nouveau mot de passe",
    newPasswordPlaceholder: "Entrez votre nouveau mot de passe",
    confirmNewPassword: "Confirmer le nouveau mot de passe",
    confirmNewPasswordPlaceholder: "Confirmez votre nouveau mot de passe",
    updatePassword: "Mettre à jour le mot de passe",
    cancel: "Annuler",
    passwordUpdated: "Mot de passe mis à jour",
    passwordUpdatedDescription: "Votre mot de passe a été modifié avec succès.",
    
    // Cookie Banner
    cookieBannerTitle: "Nous utilisons des cookies",
    cookieBannerDescription: "Nous utilisons des cookies essentiels pour le fonctionnement du site et des cookies analytiques pour améliorer votre expérience. Vous pouvez personnaliser vos préférences.",
    cookieAcceptAll: "Tout accepter",
    cookieRejectAll: "Tout refuser",
    cookieSettings: "Paramètres",
    cookieNecessary: "Cookies nécessaires",
    cookieNecessaryDescription: "Ces cookies sont essentiels au bon fonctionnement du site. Ils ne peuvent pas être désactivés.",
    cookieAnalytics: "Cookies analytiques",
    cookieAnalyticsDescription: "Ces cookies nous aident à comprendre comment les visiteurs interagissent avec notre site web en collectant et en rapportant des informations de manière anonyme.",
    cookieSettingsTitle: "Paramètres des cookies",
    cookieSettingsDescription: "Personnalisez vos préférences de cookies. Vous pouvez activer ou désactiver différents types de cookies ci-dessous.",
    cookieSavePreferences: "Enregistrer les préférences",
    legal: "Légal",
    termsConditions: "Conditions Générales",
    privacyPolicy: "Politique de Confidentialité",
    tradingRisks: "Risques de Trading",
    legalNotice: "Mentions Légales",
    copyright: "© 2025 Signaux de Trading en Temps Réel. Tous droits réservés.",
    
    // Sub-header banner
    bannerBadge: "La Plateforme la Plus Révolutionnaire",
    bannerTitle: "Market Signals24",
    bannerDescription: "La première plateforme de signaux avec triple validation : Intelligence Artificielle + Experts Humains + Confirmation Marché. Zéro tolérance pour les faux signaux.",
    bannerCta: "Découvrir Maintenant",
    
    // Above-footer promo
    promoTitle: "Pourquoi les Traders Choisissent Market Signals24 ?",
    promoSubtitle: "Rejoignez des milliers de traders qui profitent déjà de nos signaux triplement validés",
    promoStat1Title: "Triple Validation",
    promoStat1Desc: "Chaque signal passe par l'IA, des traders experts et une confirmation marché avant de vous parvenir",
    promoStat2Title: "97,2% de Précision",
    promoStat2Desc: "Notre IA élimine les faux signaux — seules les opportunités les plus fiables atteignent votre écran",
    promoStat3Title: "24/7 Temps Réel",
    promoStat3Desc: "Ne manquez jamais une opportunité — notre système surveille les marchés en continu pour vous",
    promoCta: "Commencez à Trader Plus Intelligemment",
    promoUrgency: "Places limitées — L'accès Premium pourrait fermer bientôt",
    
    // Popup
    popupTitle: "Ne Tradez Pas à l'Aveugle !",
    popupSubtitle: "93% des traders perdent de l'argent avec des signaux non vérifiés.",
    popupHighlight: "Market Signals24 est la SEULE plateforme qui triple-valide chaque signal avant de vous l'envoyer.",
    popupBullet1: "L'IA analyse plus de 10 000 points de données par seconde",
    popupBullet2: "Des traders experts confirment chaque signal manuellement",
    popupBullet3: "Les conditions du marché sont vérifiées en temps réel",
    popupCta: "Obtenez des Signaux Vérifiés Maintenant",
    popupDismiss: "Je prends le risque de trader sans vérification"
  },
  es: {
    pricingTitle: "Elige tu plan",
    pricingSubtitle: "Desbloquea señales premium y mejora tu estrategia.",
    buyWithStripe: "Comprar con Stripe",
    buyWithLabel: "O paga con crypto",
    cryptoInstantTagline: "Pago cripto instantáneo",
    cryptoPayCta: "Pagar",
    payWithCrypto: "Pagar con criptos",
    // Contenu principal
    heroTitle: "SEÑALES DE TRADING EN TIEMPO REAL IMPULSADAS POR IA",
    heroSubtitle: "Y NUESTROS TRADERS PROFESIONALES",
    heroDescription: "Aprovecha el poder de nuestra IA avanzada para obtener señales COMPRAR/VENDER de nivel institucional para mercados Forex, Índices y Crypto.",
    activeTraders: "traders activos en línea",
    
    // Boutons et actions
    signIn: "Iniciar sesión",
    signUp: "Registrarse",
    getStarted: "Comenzar",
    upgradeNow: "Actualizar ahora",
    learnMore: "Saber más",
    
    // Section d'affiliation
    affiliateTitle: "Únete a nuestro programa de afiliados",
    affiliateDescription: "Gana 35% de comisión en cada registro generado a través de tus enlaces únicos.",
    affiliateButton: "Únete al programa",
    affiliateLink: "Haz clic aquí para unirte al programa de afiliados",
    affiliateStats: "COMISIONES PAGADAS",
    affiliateEmail: "realtimetradingsignal@gmail.com",
    
    // Trading Bot Settings
    tradingBotSettings: "Configuración del Bot de Trading",
    configureTradingSettings: "Configura tus parámetros de trading",
    category: "Categoría",
    asset: "Activo",
    timeframe: "Marco temporal",
    open: "Abierto",
    closed: "Cerrado",
    logInToGetSignals: "Iniciar sesión para obtener señales",
    tutorialVideoTitle: "¿Cómo usar la plataforma de señales de trading en tiempo real?",
    tutorialVideoSubtitle: "Mira nuestra guía de tutorial completa",
    
    // Active Signals
    activeSignals: "SEÑALES ACTIVAS",
    noActiveSignals: "No hay señales activas.",
    selectSettingsFirst: "Primero selecciona la configuración, luego haz clic en Iniciar Señales, y verás la señal activa aquí.",
    startSignals: "Iniciar Señales",
    
    // Signal Notifications
    signalGenerated: "Señal generada",
    signalGeneratedDescription: "Nueva señal {type} generada para {asset} basada en análisis técnico en tiempo real",
    signalActivated: "¡Señal activada!",
    signalActivatedInfo: "Una nueva señal {type} para {asset} ha sido generada a partir del análisis de mercado en tiempo real.",
    signalExpired: "Señal expirada",
    signalExpiredDescription: "La señal activa ha expirado. Ahora puedes generar una nueva señal.",
    signalExpiredTitle: "Señal Expirada",
    signalExpiredDismiss: "Haz clic para cerrar",
    
    // Version
    versionName: "Versión 2.0 - Real-Time Precision Edition",
    
    // Footer
    footerDescription: "Señales de trading en tiempo real generadas por IA y nuestros traders profesionales",
    services: "Servicios",
    forexSignals: "Señales Forex",
    cryptoSignals: "Señales Crypto",
    indicesSignals: "Señales Índices",
    technicalAnalysis: "Análisis Técnico",
    support: "Soporte",
    customerService: "Servicio al Cliente",
    becomeAffiliate: "Convertirse en Afiliado",
    faq: "FAQ",
    
    // User Menu
    homePage: "Página de inicio",
    profileSettings: "Perfil y Configuración",
    cancelSubscription: "Cancelar Suscripción",
    manageSubscription: "Gestionar Suscripción",
    changePassword: "Cambiar Contraseña",
    suspendAccount: "Suspender Cuenta",
    deleteAccount: "Eliminar Cuenta",
    logOut: "Cerrar sesión",
    
    // Cancel Subscription Modal
    cancelSubscriptionConfirm: "¿Está seguro de que desea cancelar su suscripción? Esta acción detendrá su facturación recurrente.",
    beforeYouCancel: "Antes de cancelar:",
    cancelWarning1: "Perderá el acceso a las señales de trading premium",
    cancelWarning2: "Su suscripción finalizará en el período de facturación actual",
    cancelWarning3: "Puede volver a suscribirse en cualquier momento",
    cancelWarning4: "No hay reembolsos para el período de facturación actual",
    cancelRedirectMessage: "Será redirigido al portal seguro de Stripe para cancelar su suscripción de forma segura.",
    keepSubscription: "Mantener suscripción",
    
    // Change Password Modal
    changePasswordDescription: "Ingrese su contraseña actual y elija una nueva contraseña",
    currentPassword: "Contraseña actual",
    currentPasswordPlaceholder: "Ingrese su contraseña actual",
    newPassword: "Nueva contraseña",
    newPasswordPlaceholder: "Ingrese su nueva contraseña",
    confirmNewPassword: "Confirmar nueva contraseña",
    confirmNewPasswordPlaceholder: "Confirme su nueva contraseña",
    updatePassword: "Actualizar contraseña",
    cancel: "Cancelar",
    passwordUpdated: "Contraseña actualizada",
    passwordUpdatedDescription: "Su contraseña se ha actualizado correctamente.",
    
    // Cookie Banner
    cookieBannerTitle: "Utilizamos cookies",
    cookieBannerDescription: "Utilizamos cookies esenciales para la funcionalidad del sitio y cookies analíticas para mejorar su experiencia. Puede personalizar sus preferencias.",
    cookieAcceptAll: "Aceptar todo",
    cookieRejectAll: "Rechazar todo",
    cookieSettings: "Configuración",
    cookieNecessary: "Cookies necesarias",
    cookieNecessaryDescription: "Estas cookies son esenciales para el funcionamiento del sitio web. No se pueden desactivar.",
    cookieAnalytics: "Cookies analíticas",
    cookieAnalyticsDescription: "Estas cookies nos ayudan a entender cómo los visitantes interactúan con nuestro sitio web recopilando y reportando información de forma anónima.",
    cookieSettingsTitle: "Configuración de cookies",
    cookieSettingsDescription: "Personalice sus preferencias de cookies. Puede habilitar o deshabilitar diferentes tipos de cookies a continuación.",
    cookieSavePreferences: "Guardar preferencias",
    
    legal: "Legal",
    termsConditions: "Términos y Condiciones",
    privacyPolicy: "Política de Privacidad",
    tradingRisks: "Riesgos de Trading",
    legalNotice: "Aviso Legal",
    copyright: "© 2025 Señales de Trading en Tiempo Real. Todos los derechos reservados.",
    
    // Sub-header banner
    bannerBadge: "La Plataforma Más Revolucionaria",
    bannerTitle: "Market Signals24",
    bannerDescription: "La primera plataforma de señales con triple validación: Inteligencia Artificial + Expertos Humanos + Confirmación del Mercado. Cero tolerancia para señales falsas.",
    bannerCta: "Descubrir Ahora",
    
    // Above-footer promo
    promoTitle: "¿Por Qué los Traders Eligen Market Signals24?",
    promoSubtitle: "Únete a miles de traders que ya se benefician de nuestras señales triplemente validadas",
    promoStat1Title: "Triple Validación",
    promoStat1Desc: "Cada señal pasa por IA, traders expertos y confirmación del mercado antes de llegar a ti",
    promoStat2Title: "97,2% de Precisión",
    promoStat2Desc: "Nuestra IA elimina las señales falsas — solo las oportunidades más fiables llegan a tu pantalla",
    promoStat3Title: "24/7 Tiempo Real",
    promoStat3Desc: "Nunca pierdas una oportunidad — nuestro sistema vigila los mercados las 24 horas por ti",
    promoCta: "Empieza a Operar Más Inteligentemente Hoy",
    promoUrgency: "Plazas limitadas — El acceso Premium podría cerrarse pronto",
    
    // Popup
    popupTitle: "¡No Operes a Ciegas!",
    popupSubtitle: "El 93% de los traders pierden dinero usando señales no verificadas.",
    popupHighlight: "Market Signals24 es la ÚNICA plataforma que triple-valida cada señal antes de enviártela.",
    popupBullet1: "La IA analiza más de 10.000 puntos de datos por segundo",
    popupBullet2: "Traders expertos confirman cada señal manualmente",
    popupBullet3: "Las condiciones del mercado se verifican en tiempo real",
    popupCta: "Obtén Señales Verificadas Ahora",
    popupDismiss: "Me arriesgo a operar sin verificación"
  },
  it: {
    pricingTitle: "Scegli il tuo piano",
    pricingSubtitle: "Sblocca segnali premium e migliora la tua strategia.",
    buyWithStripe: "Acquista con Stripe",
    buyWithLabel: "Oppure paga in cripto",
    cryptoInstantTagline: "Pagamento cripto istantaneo",
    cryptoPayCta: "Paga",
    payWithCrypto: "Paga con cripto",
    // Contenu principal
    heroTitle: "SEGNALI DI TRADING IN TEMPO REALE ALIMENTATI DA IA",
    heroSubtitle: "E I NOSTRI TRADER PROFESSIONISTI",
    heroDescription: "Sfrutta il potere della nostra IA avanzata per ottenere segnali COMPRA/VENDI di livello istituzionale per i mercati Forex, Indici e Crypto.",
    activeTraders: "trader attivi online",
    
    // Boutons et actions
    signIn: "Accedi",
    signUp: "Registrati",
    getStarted: "Inizia",
    upgradeNow: "Aggiorna ora",
    learnMore: "Scopri di più",
    
    // Section d'affiliation
    affiliateTitle: "Unisciti al nostro programma di affiliazione",
    affiliateDescription: "Guadagna il 35% di commissione su ogni registrazione generata tramite i tuoi link unici.",
    affiliateButton: "Unisciti al programma",
    affiliateLink: "Clicca qui per unirti al programma di affiliazione",
    affiliateStats: "COMMISSIONI PAGATE",
    affiliateEmail: "realtimetradingsignal@gmail.com",
    
    // Trading Bot Settings
    tradingBotSettings: "Impostazioni Bot di Trading",
    configureTradingSettings: "Configura le tue impostazioni di trading",
    category: "Categoria",
    asset: "Attivo",
    timeframe: "Timeframe",
    open: "Aperto",
    closed: "Chiuso",
    logInToGetSignals: "Accedi per ottenere i segnali",
    tutorialVideoTitle: "Come utilizzare la piattaforma di segnali di trading in tempo reale?",
    tutorialVideoSubtitle: "Guarda la nostra guida tutorial completa",
    
    // Active Signals
    activeSignals: "SEGNALI ATTIVI",
    noActiveSignals: "Nessun segnale attivo.",
    selectSettingsFirst: "Prima seleziona le impostazioni, poi clicca su Inizia Segnali, e vedrai il segnale attivo qui.",
    startSignals: "Inizia Segnali",
    
    // Signal Notifications
    signalGenerated: "Segnale generato",
    signalGeneratedDescription: "Nuovo segnale {type} generato per {asset} basato sull'analisi tecnica in tempo reale",
    signalActivated: "Segnale attivato!",
    signalActivatedInfo: "Un nuovo segnale {type} per {asset} è stato generato dall'analisi di mercato in tempo reale.",
    signalExpired: "Segnale scaduto",
    signalExpiredDescription: "Il segnale attivo è scaduto. Ora puoi generare un nuovo segnale.",
    signalExpiredTitle: "Segnale Scaduto",
    signalExpiredDismiss: "Clicca per chiudere",
    
    // Version
    versionName: "Versione 2.0 - Real-Time Precision Edition",
    
    // Footer
    footerDescription: "Segnali di trading in tempo reale generati da IA e dai nostri trader professionisti",
    services: "Servizi",
    forexSignals: "Segnali Forex",
    cryptoSignals: "Segnali Crypto",
    indicesSignals: "Segnali Indici",
    technicalAnalysis: "Analisi Tecnica",
    support: "Supporto",
    customerService: "Servizio Clienti",
    becomeAffiliate: "Diventa Affiliato",
    faq: "FAQ",
    
    // User Menu
    homePage: "Pagina principale",
    profileSettings: "Profilo e Impostazioni",
    cancelSubscription: "Annulla Abbonamento",
    manageSubscription: "Gestisci Abbonamento",
    changePassword: "Cambia Password",
    suspendAccount: "Sospendi Account",
    deleteAccount: "Elimina Account",
    logOut: "Esci",
    
    // Cancel Subscription Modal
    cancelSubscriptionConfirm: "Sei sicuro di voler cancellare il tuo abbonamento? Questa azione interromperà la tua fatturazione ricorrente.",
    beforeYouCancel: "Prima di cancellare:",
    cancelWarning1: "Perderai l'accesso ai segnali di trading premium",
    cancelWarning2: "Il tuo abbonamento terminerà al periodo di fatturazione corrente",
    cancelWarning3: "Puoi riabbonarti in qualsiasi momento",
    cancelWarning4: "Nessun rimborso per il periodo di fatturazione corrente",
    cancelRedirectMessage: "Sarai reindirizzato al portale sicuro di Stripe per cancellare il tuo abbonamento in modo sicuro.",
    keepSubscription: "Mantieni abbonamento",
    
    // Change Password Modal
    changePasswordDescription: "Inserisci la tua password attuale e scegli una nuova password",
    currentPassword: "Password attuale",
    currentPasswordPlaceholder: "Inserisci la tua password attuale",
    newPassword: "Nuova password",
    newPasswordPlaceholder: "Inserisci la tua nuova password",
    confirmNewPassword: "Conferma nuova password",
    confirmNewPasswordPlaceholder: "Conferma la tua nuova password",
    updatePassword: "Aggiorna password",
    cancel: "Annulla",
    passwordUpdated: "Password aggiornata",
    passwordUpdatedDescription: "La tua password è stata aggiornata con successo.",
    
    // Cookie Banner
    cookieBannerTitle: "Utilizziamo i cookie",
    cookieBannerDescription: "Utilizziamo cookie essenziali per la funzionalità del sito e cookie analitici per migliorare la tua esperienza. Puoi personalizzare le tue preferenze.",
    cookieAcceptAll: "Accetta tutto",
    cookieRejectAll: "Rifiuta tutto",
    cookieSettings: "Impostazioni",
    cookieNecessary: "Cookie necessari",
    cookieNecessaryDescription: "Questi cookie sono essenziali per il corretto funzionamento del sito web. Non possono essere disattivati.",
    cookieAnalytics: "Cookie analitici",
    cookieAnalyticsDescription: "Questi cookie ci aiutano a capire come i visitatori interagiscono con il nostro sito web raccogliendo e riportando informazioni in modo anonimo.",
    cookieSettingsTitle: "Impostazioni cookie",
    cookieSettingsDescription: "Personalizza le tue preferenze sui cookie. Puoi abilitare o disabilitare diversi tipi di cookie di seguito.",
    cookieSavePreferences: "Salva preferenze",
    
    legal: "Legale",
    termsConditions: "Termini e Condizioni",
    privacyPolicy: "Informativa sulla Privacy",
    tradingRisks: "Rischi di Trading",
    legalNotice: "Note Legali",
    copyright: "© 2025 Segnali di Trading in Tempo Reale. Tutti i diritti riservati.",
    
    // Sub-header banner
    bannerBadge: "La Piattaforma Più Rivoluzionaria",
    bannerTitle: "Market Signals24",
    bannerDescription: "La prima piattaforma di segnali con tripla validazione: Intelligenza Artificiale + Esperti Umani + Conferma del Mercato. Zero tolleranza per i segnali falsi.",
    bannerCta: "Scopri Ora",
    
    // Above-footer promo
    promoTitle: "Perché i Trader Scelgono Market Signals24?",
    promoSubtitle: "Unisciti a migliaia di trader che già beneficiano dei nostri segnali triplamente validati",
    promoStat1Title: "Tripla Validazione",
    promoStat1Desc: "Ogni segnale passa attraverso IA, trader esperti e conferma del mercato prima di raggiungerti",
    promoStat2Title: "97,2% di Precisione",
    promoStat2Desc: "La nostra IA elimina i segnali falsi — solo le opportunità più affidabili raggiungono il tuo schermo",
    promoStat3Title: "24/7 Tempo Reale",
    promoStat3Desc: "Non perdere mai un'opportunità — il nostro sistema monitora i mercati 24 ore su 24 per te",
    promoCta: "Inizia a Fare Trading in Modo Più Intelligente Oggi",
    promoUrgency: "Posti limitati — L'accesso Premium potrebbe chiudersi presto",
    
    // Popup
    popupTitle: "Non Fare Trading alla Cieca!",
    popupSubtitle: "Il 93% dei trader perde denaro usando segnali non verificati.",
    popupHighlight: "Market Signals24 è l'UNICA piattaforma che tripla-valida ogni segnale prima di inviartelo.",
    popupBullet1: "L'IA analizza più di 10.000 punti dati al secondo",
    popupBullet2: "Trader esperti confermano ogni segnale manualmente",
    popupBullet3: "Le condizioni di mercato sono verificate in tempo reale",
    popupCta: "Ottieni Segnali Verificati Ora",
    popupDismiss: "Mi prendo il rischio di fare trading senza verifica"
  },
  pt: {
    pricingTitle: "Escolha seu plano",
    pricingSubtitle: "Desbloqueie sinais premium e melhore sua estratégia.",
    buyWithStripe: "Comprar com Stripe",
    buyWithLabel: "Ou pague com cripto",
    cryptoInstantTagline: "Pagamento cripto instantâneo",
    cryptoPayCta: "ESCOLHER",
    payWithCrypto: "Pagamento Criptomoeda",
    cryptoPaymentSubtext: "BTC, ETH, USDT e mais de 150 criptos",
    // Contenu principal
    heroTitle: "SINAIS DE TRADING EM TEMPO REAL ALIMENTADOS POR IA",
    heroSubtitle: "E NOSSOS TRADERS PROFISSIONAIS",
    heroDescription: "Aproveite o poder da nossa IA avançada para obter sinais COMPRAR/VENDER de nível institucional para mercados Forex, Índices e Crypto.",
    activeTraders: "traders ativos online",
    
    // Boutons et actions
    signIn: "Entrar",
    signUp: "Registrar",
    getStarted: "Começar",
    upgradeNow: "Atualizar agora",
    learnMore: "Saber mais",
    
    // Section d'affiliation
    affiliateTitle: "Junte-se ao nosso programa de afiliados",
    affiliateDescription: "Ganhe 35% de comissão em cada registro gerado através dos seus links únicos.",
    affiliateButton: "Juntar-se ao programa",
    affiliateLink: "Clique aqui para se juntar ao programa de afiliados",
    affiliateStats: "COMISSÕES PAGAS",
    affiliateEmail: "realtimetradingsignal@gmail.com",
    
    // Trading Bot Settings
    tradingBotSettings: "Configurações do Bot de Trading",
    configureTradingSettings: "Configure suas configurações de trading",
    category: "Categoria",
    asset: "Ativo",
    timeframe: "Timeframe",
    open: "Aberto",
    closed: "Fechado",
    logInToGetSignals: "Entrar para obter sinais",
    tutorialVideoTitle: "Como usar a plataforma de sinais de trading em tempo real?",
    tutorialVideoSubtitle: "Assista ao nosso guia de tutorial completo",
    
    // Active Signals
    activeSignals: "SINAIS ATIVOS",
    noActiveSignals: "Nenhum sinal ativo.",
    selectSettingsFirst: "Primeiro selecione as configurações, depois clique em Iniciar Sinais, e você verá o sinal ativo aqui.",
    startSignals: "Iniciar Sinais",
    
    // Signal Notifications
    signalGenerated: "Sinal gerado",
    signalGeneratedDescription: "Novo sinal {type} gerado para {asset} baseado em análise técnica em tempo real",
    signalActivated: "Sinal ativado!",
    signalActivatedInfo: "Um novo sinal {type} para {asset} foi gerado a partir da análise de mercado em tempo real.",
    signalExpired: "Sinal expirado",
    signalExpiredDescription: "O sinal ativo expirou. Agora você pode gerar um novo sinal.",
    signalExpiredTitle: "Sinal Expirado",
    signalExpiredDismiss: "Clique para fechar",
    
    // Version
    versionName: "Versão 2.0 - Real-Time Precision Edition",
    
    // Footer
    footerDescription: "Sinais de trading em tempo real gerados por IA e nossos traders profissionais",
    services: "Serviços",
    forexSignals: "Sinais Forex",
    cryptoSignals: "Sinais Crypto",
    indicesSignals: "Sinais Índices",
    technicalAnalysis: "Análise Técnica",
    support: "Suporte",
    customerService: "Atendimento ao Cliente",
    becomeAffiliate: "Tornar-se Afiliado",
    faq: "FAQ",
    legal: "Legal",
    termsConditions: "Termos e Condições",
    privacyPolicy: "Política de Privacidade",
    tradingRisks: "Riscos de Trading",
    legalNotice: "Aviso Legal",
    copyright: "© 2025 Sinais de Trading em Tempo Real. Todos os direitos reservados.",
    
    // User Menu
    homePage: "Página inicial",
    profileSettings: "Perfil e Configurações",
    cancelSubscription: "Cancelar Assinatura",
    manageSubscription: "Gerenciar Assinatura",
    changePassword: "Alterar Senha",
    suspendAccount: "Suspender Conta",
    deleteAccount: "Excluir Conta",
    logOut: "Sair",
    
    // Cancel Subscription Modal
    cancelSubscriptionConfirm: "Tem certeza de que deseja cancelar sua assinatura? Esta ação interromperá sua cobrança recorrente.",
    beforeYouCancel: "Antes de cancelar:",
    cancelWarning1: "Você perderá o acesso aos sinais de trading premium",
    cancelWarning2: "Sua assinatura terminará no período de faturamento atual",
    cancelWarning3: "Você pode se reinscrever a qualquer momento",
    cancelWarning4: "Sem reembolsos para o período de faturamento atual",
    cancelRedirectMessage: "Você será redirecionado para o portal seguro do Stripe para cancelar sua assinatura com segurança.",
    keepSubscription: "Manter assinatura",
    
    // Change Password Modal
    changePasswordDescription: "Digite sua senha atual e escolha uma nova senha",
    currentPassword: "Senha atual",
    currentPasswordPlaceholder: "Digite sua senha atual",
    newPassword: "Nova senha",
    newPasswordPlaceholder: "Digite sua nova senha",
    confirmNewPassword: "Confirmar nova senha",
    confirmNewPasswordPlaceholder: "Confirme sua nova senha",
    updatePassword: "Atualizar senha",
    cancel: "Cancelar",
    passwordUpdated: "Senha atualizada",
    passwordUpdatedDescription: "Sua senha foi atualizada com sucesso.",
    
    // Cookie Banner
    cookieBannerTitle: "Usamos cookies",
    cookieBannerDescription: "Usamos cookies essenciais para a funcionalidade do site e cookies analíticos para melhorar sua experiência. Você pode personalizar suas preferências.",
    cookieAcceptAll: "Aceitar tudo",
    cookieRejectAll: "Rejeitar tudo",
    cookieSettings: "Configurações",
    cookieNecessary: "Cookies necessários",
    cookieNecessaryDescription: "Estes cookies são essenciais para o funcionamento do site. Eles não podem ser desativados.",
    cookieAnalytics: "Cookies analíticos",
    cookieAnalyticsDescription: "Estes cookies nos ajudam a entender como os visitantes interagem com nosso site coletando e relatando informações anonimamente.",
    cookieSettingsTitle: "Configurações de cookies",
    cookieSettingsDescription: "Personalize suas preferências de cookies. Você pode ativar ou desativar diferentes tipos de cookies abaixo.",
    cookieSavePreferences: "Salvar preferências",
    
    // Sub-header banner
    bannerBadge: "A Plataforma Mais Revolucionária",
    bannerTitle: "Market Signals24",
    bannerDescription: "A primeira plataforma de sinais com tripla validação: Inteligência Artificial + Especialistas Humanos + Confirmação do Mercado. Zero tolerância para sinais falsos.",
    bannerCta: "Descubra Agora",
    
    // Above-footer promo
    promoTitle: "Por Que os Traders Escolhem o Market Signals24?",
    promoSubtitle: "Junte-se a milhares de traders que já lucram com nossos sinais triplamente validados",
    promoStat1Title: "Tripla Validação",
    promoStat1Desc: "Cada sinal passa pela IA, traders especialistas e confirmação do mercado antes de chegar a você",
    promoStat2Title: "97,2% de Precisão",
    promoStat2Desc: "Nossa IA elimina sinais falsos — apenas as oportunidades mais confiáveis chegam à sua tela",
    promoStat3Title: "24/7 Tempo Real",
    promoStat3Desc: "Nunca perca uma oportunidade — nosso sistema monitora os mercados 24 horas por dia para você",
    promoCta: "Comece a Operar de Forma Mais Inteligente Hoje",
    promoUrgency: "Vagas limitadas — O acesso Premium pode fechar em breve",
    
    // Popup
    popupTitle: "Não Opere no Escuro!",
    popupSubtitle: "93% dos traders perdem dinheiro usando sinais não verificados.",
    popupHighlight: "O Market Signals24 é a ÚNICA plataforma que tripla-valida cada sinal antes de enviá-lo a você.",
    popupBullet1: "A IA analisa mais de 10.000 pontos de dados por segundo",
    popupBullet2: "Traders especialistas confirmam cada sinal manualmente",
    popupBullet3: "As condições do mercado são verificadas em tempo real",
    popupCta: "Obtenha Sinais Verificados Agora",
    popupDismiss: "Eu arrisco operar sem verificação"
  },
  ru: {
    pricingTitle: "Выберите тариф",
    pricingSubtitle: "Получайте премиальные сигналы и улучшайте стратегию.",
    buyWithStripe: "Оплатить через Stripe",
    buyWithLabel: "Или оплатите криптовалютой",
    cryptoInstantTagline: "Мгновенный крипто-платеж",
    cryptoPayCta: "ВЫБРАТЬ",
    payWithCrypto: "Оплата Криптовалютой",
    cryptoPaymentSubtext: "BTC, ETH, USDT и более 150 крипто",
    // Contenu principal
    heroTitle: "СИГНАЛЫ ТОРГОВЛИ В РЕАЛЬНОМ ВРЕМЕНИ НА ОСНОВЕ ИИ",
    heroSubtitle: "И НАШИ ПРОФЕССИОНАЛЬНЫЕ ТРЕЙДЕРЫ",
    heroDescription: "Используйте силу нашего продвинутого ИИ для получения институциональных сигналов ПОКУПАТЬ/ПРОДАВАТЬ для рынков Forex, Индексов и Крипто.",
    activeTraders: "активных трейдеров онлайн",
    
    // Boutons et actions
    signIn: "Войти",
    signUp: "Зарегистрироваться",
    getStarted: "Начать",
    upgradeNow: "Обновить сейчас",
    learnMore: "Узнать больше",
    
    // Section d'affiliation
    affiliateTitle: "Присоединяйтесь к нашей партнерской программе",
    affiliateDescription: "Зарабатывайте 35% комиссии с каждой регистрации, сгенерированной через ваши уникальные ссылки.",
    affiliateButton: "Присоединиться к программе",
    affiliateLink: "Нажмите здесь, чтобы присоединиться к партнерской программе",
    affiliateStats: "ВЫПЛАЧЕННЫЕ КОМИССИИ",
    affiliateEmail: "realtimetradingsignal@gmail.com",
    
    // Trading Bot Settings
    tradingBotSettings: "Настройки Торгового Бота",
    configureTradingSettings: "Настройте параметры торговли",
    category: "Категория",
    asset: "Актив",
    timeframe: "Временной интервал",
    open: "Открыто",
    closed: "Закрыто",
    logInToGetSignals: "Войти для получения сигналов",
    tutorialVideoTitle: "Как использовать платформу сигналов трейдинга в реальном времени?",
    tutorialVideoSubtitle: "Посмотрите наш полный обучающий гид",
    
    // Active Signals
    activeSignals: "АКТИВНЫЕ СИГНАЛЫ",
    noActiveSignals: "Нет активных сигналов.",
    selectSettingsFirst: "Сначала выберите настройки, затем нажмите Начать Сигналы, и вы увидите активный сигнал здесь.",
    startSignals: "Начать Сигналы",
    
    // Signal Notifications
    signalGenerated: "Сигнал сгенерирован",
    signalGeneratedDescription: "Новый сигнал {type} сгенерирован для {asset} на основе технического анализа в реальном времени",
    signalActivated: "Сигнал активирован!",
    signalActivatedInfo: "Новый сигнал {type} для {asset} был сгенерирован на основе анализа рынка в реальном времени.",
    signalExpired: "Сигнал истек",
    signalExpiredDescription: "Активный сигнал истек. Теперь вы можете сгенерировать новый сигнал.",
    signalExpiredTitle: "Сигнал Истек",
    signalExpiredDismiss: "Нажмите, чтобы закрыть",
    
    // Version
    versionName: "Версия 2.0 - Real-Time Precision Edition",
    
    // Footer
    footerDescription: "Сигналы торговли в реальном времени, сгенерированные ИИ и нашими профессиональными трейдерами",
    services: "Услуги",
    forexSignals: "Форекс Сигналы",
    cryptoSignals: "Крипто Сигналы",
    indicesSignals: "Индексы Сигналы",
    technicalAnalysis: "Технический Анализ",
    support: "Поддержка",
    customerService: "Служба поддержки",
    becomeAffiliate: "Стать партнером",
    faq: "FAQ",
    legal: "Юридическая информация",
    termsConditions: "Условия использования",
    privacyPolicy: "Политика конфиденциальности",
    tradingRisks: "Риски торговли",
    legalNotice: "Юридическое уведомление",
    copyright: "© 2025 Сигналы Торговли в Реальном Времени. Все права защищены.",
    
    // User Menu
    homePage: "Главная страница",
    profileSettings: "Профиль и Настройки",
    cancelSubscription: "Отменить подписку",
    manageSubscription: "Управление подпиской",
    changePassword: "Изменить пароль",
    suspendAccount: "Приостановить аккаунт",
    deleteAccount: "Удалить аккаунт",
    logOut: "Выйти",
    
    // Cancel Subscription Modal
    cancelSubscriptionConfirm: "Вы уверены, что хотите отменить подписку? Это действие остановит вашу повторяющуюся оплату.",
    beforeYouCancel: "Перед отменой:",
    cancelWarning1: "Вы потеряете доступ к премиум торговым сигналам",
    cancelWarning2: "Ваша подписка закончится в текущем периоде оплаты",
    cancelWarning3: "Вы можете подписаться снова в любое время",
    cancelWarning4: "Нет возмещений за текущий период оплаты",
    cancelRedirectMessage: "Вы будете перенаправлены на защищенный портал Stripe для безопасной отмены подписки.",
    keepSubscription: "Сохранить подписку",
    
    // Change Password Modal
    changePasswordDescription: "Введите ваш текущий пароль и выберите новый пароль",
    currentPassword: "Текущий пароль",
    currentPasswordPlaceholder: "Введите ваш текущий пароль",
    newPassword: "Новый пароль",
    newPasswordPlaceholder: "Введите ваш новый пароль",
    confirmNewPassword: "Подтвердить новый пароль",
    confirmNewPasswordPlaceholder: "Подтвердите ваш новый пароль",
    updatePassword: "Обновить пароль",
    cancel: "Отмена",
    passwordUpdated: "Пароль обновлен",
    passwordUpdatedDescription: "Ваш пароль был успешно изменен.",
    
    // Cookie Banner
    cookieBannerTitle: "Мы используем cookies",
    cookieBannerDescription: "Мы используем необходимые cookies для функциональности сайта и аналитические cookies для улучшения вашего опыта. Вы можете настроить свои предпочтения.",
    cookieAcceptAll: "Принять все",
    cookieRejectAll: "Отклонить все",
    cookieSettings: "Настройки",
    cookieNecessary: "Необходимые cookies",
    cookieNecessaryDescription: "Эти cookies необходимы для работы веб-сайта. Они не могут быть отключены.",
    cookieAnalytics: "Аналитические cookies",
    cookieAnalyticsDescription: "Эти cookies помогают нам понять, как посетители взаимодействуют с нашим веб-сайтом, собирая и сообщая информацию анонимно.",
    cookieSettingsTitle: "Настройки cookies",
    cookieSettingsDescription: "Настройте свои предпочтения cookies. Вы можете включить или отключить различные типы cookies ниже.",
    cookieSavePreferences: "Сохранить предпочтения",
    
    // Sub-header banner
    bannerBadge: "Самая Революционная Платформа",
    bannerTitle: "Market Signals24",
    bannerDescription: "Первая платформа сигналов с тройной проверкой: Искусственный Интеллект + Эксперты-Люди + Подтверждение Рынка. Нулевая толерантность к ложным сигналам.",
    bannerCta: "Узнать Сейчас",
    
    // Above-footer promo
    promoTitle: "Почему Трейдеры Выбирают Market Signals24?",
    promoSubtitle: "Присоединяйтесь к тысячам трейдеров, которые уже зарабатывают на наших тройно проверенных сигналах",
    promoStat1Title: "Тройная Проверка",
    promoStat1Desc: "Каждый сигнал проходит через ИИ, команду экспертов и подтверждение рынка перед отправкой вам",
    promoStat2Title: "97,2% Точности",
    promoStat2Desc: "Наш ИИ устраняет ложные сигналы — только самые надежные возможности попадают на ваш экран",
    promoStat3Title: "24/7 В Реальном Времени",
    promoStat3Desc: "Не упустите ни одной возможности — наша система контролирует рынки круглосуточно для вас",
    promoCta: "Начните Торговать Умнее Сегодня",
    promoUrgency: "Ограниченное количество мест — Премиум доступ может закрыться скоро",
    
    // Popup
    popupTitle: "Не Торгуйте Вслепую!",
    popupSubtitle: "93% трейдеров теряют деньги, используя непроверенные сигналы.",
    popupHighlight: "Market Signals24 — ЕДИНСТВЕННАЯ платформа, которая тройно проверяет каждый сигнал перед отправкой вам.",
    popupBullet1: "ИИ анализирует более 10 000 точек данных в секунду",
    popupBullet2: "Эксперты-трейдеры подтверждают каждый сигнал вручную",
    popupBullet3: "Рыночные условия проверяются в режиме реального времени",
    popupCta: "Получите Проверенные Сигналы Сейчас",
    popupDismiss: "Я рискну торговать без проверки"
  },
  ar: {
    pricingTitle: "اختر خطتك",
    pricingSubtitle: "افتح إشارات مميزة وحسّن استراتيجيتك.",
    buyWithStripe: "اشترِ عبر Stripe",
    buyWithLabel: "أو ادفع بالعملات المشفرة",
    cryptoInstantTagline: "دفع فوري بالعملات المشفرة",
    cryptoPayCta: "اختر",
    payWithCrypto: "الدفع بالعملات المشفرة",
    cryptoPaymentSubtext: "BTC و ETH و USDT وأكثر من 150 عملة",
    // Contenu principal
    heroTitle: "إشارات التداول في الوقت الفعلي مدعومة بالذكاء الاصطناعي",
    heroSubtitle: "وتجارنا المحترفون",
    heroDescription: "استفد من قوة الذكاء الاصطناعي المتقدم للحصول على إشارات شراء/بيع على مستوى المؤسسات لأسواق الفوركس والمؤشرات والعملات المشفرة.",
    activeTraders: "تاجر نشط على الإنترنت",
    
    // Boutons et actions
    signIn: "تسجيل الدخول",
    signUp: "التسجيل",
    getStarted: "ابدأ",
    upgradeNow: "ترقية الآن",
    learnMore: "اعرف المزيد",
    
    // Section d'affiliation
    affiliateTitle: "انضم إلى برنامج الشراكة الخاص بنا",
    affiliateDescription: "اكسب 35% عمولة على كل تسجيل يتم إنشاؤه عبر روابطك الفريدة.",
    affiliateButton: "انضم إلى البرنامج",
    affiliateLink: "انقر هنا للانضمام إلى برنامج الشراكة",
    affiliateStats: "العمولات المدفوعة",
    affiliateEmail: "realtimetradingsignal@gmail.com",
    
    // Trading Bot Settings
    tradingBotSettings: "إعدادات بوت التداول",
    configureTradingSettings: "قم بتكوين إعدادات التداول الخاصة بك",
    category: "الفئة",
    asset: "الأصل",
    timeframe: "الإطار الزمني",
    open: "مفتوح",
    closed: "مغلق",
    logInToGetSignals: "تسجيل الدخول للحصول على الإشارات",
    tutorialVideoTitle: "كيفية استخدام منصة إشارات التداول في الوقت الفعلي؟",
    tutorialVideoSubtitle: "شاهد دليلنا التعليمي الشامل",
    
    // Active Signals
    activeSignals: "الإشارات النشطة",
    noActiveSignals: "لا توجد إشارات نشطة.",
    selectSettingsFirst: "أولاً اختر الإعدادات، ثم انقر على بدء الإشارات، وسترى الإشارة النشطة هنا.",
    startSignals: "بدء الإشارات",
    
    // Signal Notifications
    signalGenerated: "تم إنشاء الإشارة",
    signalGeneratedDescription: "تم إنشاء إشارة {type} جديدة لـ {asset} بناءً على التحليل الفني في الوقت الفعلي",
    signalActivated: "تم تفعيل الإشارة!",
    signalActivatedInfo: "تم إنشاء إشارة {type} جديدة لـ {asset} من تحليل السوق في الوقت الفعلي.",
    signalExpired: "انتهت صلاحية الإشارة",
    signalExpiredDescription: "انتهت صلاحية الإشارة النشطة. يمكنك الآن إنشاء إشارة جديدة.",
    signalExpiredTitle: "انتهت صلاحية الإشارة",
    signalExpiredDismiss: "انقر للإغلاق",
    
    // Version
    versionName: "الإصدار 2.0 - Real-Time Precision Edition",
    
    // Footer
    footerDescription: "إشارات التداول في الوقت الفعلي التي تم إنشاؤها بواسطة الذكاء الاصطناعي وتجارنا المحترفين",
    services: "الخدمات",
    forexSignals: "إشارات الفوركس",
    cryptoSignals: "إشارات العملات المشفرة",
    indicesSignals: "إشارات المؤشرات",
    technicalAnalysis: "التحليل الفني",
    support: "الدعم",
    customerService: "خدمة العملاء",
    becomeAffiliate: "تصبح شريك",
    faq: "الأسئلة الشائعة",
    legal: "قانوني",
    termsConditions: "الشروط والأحكام",
    privacyPolicy: "سياسة الخصوصية",
    tradingRisks: "مخاطر التداول",
    legalNotice: "إشعار قانوني",
    copyright: "© 2025 إشارات التداول في الوقت الفعلي. جميع الحقوق محفوظة.",
    
    // User Menu
    homePage: "الصفحة الرئيسية",
    profileSettings: "الملف الشخصي والإعدادات",
    cancelSubscription: "إلغاء الاشتراك",
    manageSubscription: "إدارة الاشتراك",
    changePassword: "تغيير كلمة المرور",
    suspendAccount: "تعليق الحساب",
    deleteAccount: "حذف الحساب",
    logOut: "تسجيل الخروج",
    
    // Cancel Subscription Modal
    cancelSubscriptionConfirm: "هل أنت متأكد أنك تريد إلغاء الاشتراك؟ سيوقف هذا الإجراء الفوترة المتكررة الخاصة بك.",
    beforeYouCancel: "قبل الإلغاء:",
    cancelWarning1: "ستفقد الوصول إلى إشارات التداول المميزة",
    cancelWarning2: "سينتهي اشتراكك في فترة الفوترة الحالية",
    cancelWarning3: "يمكنك إعادة الاشتراك في أي وقت",
    cancelWarning4: "لا توجد استردادات لفترة الفوترة الحالية",
    cancelRedirectMessage: "سيتم إعادة توجيهك إلى البوابة الآمنة لـ Stripe لإلغاء اشتراكك بأمان.",
    keepSubscription: "الاحتفاظ بالاشتراك",
    
    // Change Password Modal
    changePasswordDescription: "أدخل كلمة المرور الحالية واختر كلمة مرور جديدة",
    currentPassword: "كلمة المرور الحالية",
    currentPasswordPlaceholder: "أدخل كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    newPasswordPlaceholder: "أدخل كلمة المرور الجديدة",
    confirmNewPassword: "تأكيد كلمة المرور الجديدة",
    confirmNewPasswordPlaceholder: "أكد كلمة المرور الجديدة",
    updatePassword: "تحديث كلمة المرور",
    cancel: "إلغاء",
    passwordUpdated: "تم تحديث كلمة المرور",
    passwordUpdatedDescription: "تم تغيير كلمة المرور الخاصة بك بنجاح.",
    
    // Cookie Banner
    cookieBannerTitle: "نستخدم ملفات تعريف الارتباط",
    cookieBannerDescription: "نستخدم ملفات تعريف الارتباط الأساسية لوظائف الموقع وملفات تعريف الارتباط التحليلية لتحسين تجربتك. يمكنك تخصيص تفضيلاتك.",
    cookieAcceptAll: "قبول الكل",
    cookieRejectAll: "رفض الكل",
    cookieSettings: "الإعدادات",
    cookieNecessary: "ملفات تعريف الارتباط الضرورية",
    cookieNecessaryDescription: "هذه الملفات ضرورية لعمل الموقع بشكل صحيح. لا يمكن تعطيلها.",
    cookieAnalytics: "ملفات تعريف الارتباط التحليلية",
    cookieAnalyticsDescription: "تساعدنا هذه الملفات على فهم كيفية تفاعل الزوار مع موقعنا من خلال جمع المعلومات والإبلاغ عنها بشكل مجهول.",
    cookieSettingsTitle: "إعدادات ملفات تعريف الارتباط",
    cookieSettingsDescription: "خصص تفضيلات ملفات تعريف الارتباط الخاصة بك. يمكنك تفعيل أو إلغاء تفعيل أنواع مختلفة من ملفات تعريف الارتباط أدناه.",
    cookieSavePreferences: "حفظ التفضيلات",
    
    // Sub-header banner
    bannerBadge: "المنصة الأكثر ثورية",
    bannerTitle: "Market Signals24",
    bannerDescription: "أول منصة إشارات مع التحقق الثلاثي: الذكاء الاصطناعي + خبراء بشريون + تأكيد السوق. عدم التسامح مطلقاً مع الإشارات الكاذبة.",
    bannerCta: "اكتشف الآن",
    
    // Above-footer promo
    promoTitle: "لماذا يختار المتداولون Market Signals24؟",
    promoSubtitle: "انضم إلى آلاف المتداولين الذين يستفيدون بالفعل من إشاراتنا المعتمدة ثلاثياً",
    promoStat1Title: "تحقق ثلاثي",
    promoStat1Desc: "كل إشارة تمر عبر الذكاء الاصطناعي والمتداولين الخبراء وتأكيد السوق قبل أن تصل إليك",
    promoStat2Title: "97.2% دقة",
    promoStat2Desc: "ذكاؤنا الاصطناعي يزيل الإشارات الكاذبة — فقط الفرص الأكثر موثوقية تصل إلى شاشتك",
    promoStat3Title: "24/7 في الوقت الفعلي",
    promoStat3Desc: "لا تفوت أي فرصة أبداً — نظامنا يراقب الأسواق على مدار الساعة من أجلك",
    promoCta: "ابدأ التداول بذكاء اليوم",
    promoUrgency: "أماكن محدودة — قد يُغلق الوصول المميز قريباً",
    
    // Popup
    popupTitle: "لا تتداول بشكل أعمى!",
    popupSubtitle: "93% من المتداولين يخسرون أموالهم باستخدام إشارات غير موثقة.",
    popupHighlight: "Market Signals24 هي المنصة الوحيدة التي تتحقق ثلاثياً من كل إشارة قبل إرسالها إليك.",
    popupBullet1: "الذكاء الاصطناعي يحلل أكثر من 10,000 نقطة بيانات في الثانية",
    popupBullet2: "متداولون خبراء يؤكدون كل إشارة يدوياً",
    popupBullet3: "يتم التحقق من ظروف السوق في الوقت الفعلي",
    popupCta: "احصل على إشارات موثقة الآن",
    popupDismiss: "سأخاطر بالتداول بدون تحقق"
  },
  hi: {
    pricingTitle: "अपनी योजना चुनें",
    pricingSubtitle: "प्रीमियम सिग्नल अनलॉक करें और अपनी रणनीति सुधारें।",
    buyWithStripe: "Stripe से खरीदें",
    buyWithLabel: "या क्रिप्टो से भुगतान करें",
    cryptoInstantTagline: "तुरंत क्रिप्टो भुगतान",
    cryptoPayCta: "चुनें",
    payWithCrypto: "क्रिप्टोकरेंसी भुगतान",
    cryptoPaymentSubtext: "BTC, ETH, USDT और 150+ से अधिक",
    // Contenu principal
    heroTitle: "AI-संचालित रियल-टाइम ट्रेडिंग सिग्नल",
    heroSubtitle: "और हमारे पेशेवर ट्रेडर",
    heroDescription: "फॉरेक्स, इंडेक्स और क्रिप्टो बाजारों के लिए संस्थागत-ग्रेड खरीद/बेच सिग्नल प्राप्त करने के लिए हमारी उन्नत AI की शक्ति का उपयोग करें।",
    activeTraders: "सक्रिय ट्रेडर ऑनलाइन",
    
    // Boutons et actions
    signIn: "साइन इन",
    signUp: "साइन अप",
    getStarted: "शुरू करें",
    upgradeNow: "अभी अपग्रेड करें",
    learnMore: "और जानें",
    
    // Section d'affiliation
    affiliateTitle: "हमारे सहयोग कार्यक्रम में शामिल हों",
    affiliateDescription: "आपके अद्वितीय लिंक के माध्यम से उत्पन्न प्रत्येक पंजीकरण पर 35% कमीशन कमाएं।",
    affiliateButton: "कार्यक्रम में शामिल हों",
    affiliateLink: "सहयोग कार्यक्रम में शामिल होने के लिए यहां क्लिक करें",
    affiliateStats: "भुगतान किए गए कमीशन",
    affiliateEmail: "realtimetradingsignal@gmail.com",
    
    // Trading Bot Settings
    tradingBotSettings: "ट्रेडिंग बॉट सेटिंग्स",
    configureTradingSettings: "अपनी ट्रेडिंग सेटिंग्स कॉन्फ़िगर करें",
    category: "श्रेणी",
    asset: "संपत्ति",
    timeframe: "समय सीमा",
    open: "खुला",
    closed: "बंद",
    logInToGetSignals: "सिग्नल प्राप्त करने के लिए लॉग इन करें",
    tutorialVideoTitle: "रियल-टाइम ट्रेडिंग सिग्नल प्लेटफॉर्म का उपयोग कैसे करें?",
    tutorialVideoSubtitle: "हमारा व्यापक ट्यूटोरियल गाइड देखें",
    
    // Active Signals
    activeSignals: "सक्रिय सिग्नल",
    noActiveSignals: "कोई सक्रिय सिग्नल नहीं।",
    selectSettingsFirst: "पहले सेटिंग्स चुनें, फिर स्टार्ट सिग्नल पर क्लिक करें, और आप यहां सक्रिय सिग्नल देखेंगे।",
    startSignals: "सिग्नल शुरू करें",
    
    // Signal Notifications
    signalGenerated: "सिग्नल जेनरेट किया गया",
    signalGeneratedDescription: "{asset} के लिए {type} सिग्नल वास्तविक समय तकनीकी विश्लेषण के आधार पर जेनरेट किया गया",
    signalActivated: "सिग्नल सक्रिय!",
    signalActivatedInfo: "{asset} के लिए एक नया {type} सिग्नल वास्तविक समय बाजार विश्लेषण से जेनरेट किया गया है।",
    signalExpired: "सिग्नल समाप्त हो गया",
    signalExpiredDescription: "सक्रिय सिग्नल समाप्त हो गया है। अब आप एक नया सिग्नल जेनरेट कर सकते हैं।",
    signalExpiredTitle: "सिग्नल समाप्त",
    signalExpiredDismiss: "बंद करने के लिए क्लिक करें",
    
    // Version
    versionName: "संस्करण 2.0 - Real-Time Precision Edition",
    
    // Footer
    footerDescription: "AI और हमारे पेशेवर ट्रेडरों द्वारा उत्पन्न रियल-टाइम ट्रेडिंग सिग्नल",
    services: "सेवाएं",
    forexSignals: "फॉरेक्स सिग्नल",
    cryptoSignals: "क्रिप्टो सिग्नल",
    indicesSignals: "इंडेक्स सिग्नल",
    technicalAnalysis: "तकनीकी विश्लेषण",
    support: "सहायता",
    customerService: "ग्राहक सेवा",
    becomeAffiliate: "सहयोगी बनें",
    faq: "FAQ",
    legal: "कानूनी",
    termsConditions: "नियम और शर्तें",
    privacyPolicy: "गोपनीयता नीति",
    tradingRisks: "ट्रेडिंग जोखिम",
    legalNotice: "कानूनी नोटिस",
    copyright: "© 2025 रियल-टाइम ट्रेडिंग सिग्नल। सभी अधिकार सुरक्षित।",
    
    // User Menu
    homePage: "होम पेज",
    profileSettings: "प्रोफ़ाइल और सेटिंग्स",
    cancelSubscription: "सदस्यता रद्द करें",
    manageSubscription: "सदस्यता प्रबंधित करें",
    changePassword: "पासवर्ड बदलें",
    suspendAccount: "खाता निलंबित करें",
    deleteAccount: "खाता हटाएं",
    logOut: "लॉग आउट",
    
    // Cancel Subscription Modal
    cancelSubscriptionConfirm: "क्या आप वाकई अपनी सदस्यता रद्द करना चाहते हैं? यह कार्रवाई आपके आवर्ती बिलिंग को रोक देगी।",
    beforeYouCancel: "रद्द करने से पहले:",
    cancelWarning1: "आप प्रीमियम ट्रेडिंग सिग्नल तक पहुंच खो देंगे",
    cancelWarning2: "आपकी सदस्यता वर्तमान बिलिंग अवधि में समाप्त हो जाएगी",
    cancelWarning3: "आप कभी भी पुनः सदस्यता ले सकते हैं",
    cancelWarning4: "वर्तमान बिलिंग अवधि के लिए कोई धनवापसी नहीं",
    cancelRedirectMessage: "आपको अपनी सदस्यता को सुरक्षित रूप से रद्द करने के लिए Stripe के सुरक्षित पोर्टल पर पुनर्निर्देशित किया जाएगा।",
    keepSubscription: "सदस्यता रखें",
    
    // Change Password Modal
    changePasswordDescription: "अपना वर्तमान पासवर्ड दर्ज करें और एक नया पासवर्ड चुनें",
    currentPassword: "वर्तमान पासवर्ड",
    currentPasswordPlaceholder: "अपना वर्तमान पासवर्ड दर्ज करें",
    newPassword: "नया पासवर्ड",
    newPasswordPlaceholder: "अपना नया पासवर्ड दर्ज करें",
    confirmNewPassword: "नया पासवर्ड पुष्टि करें",
    confirmNewPasswordPlaceholder: "अपना नया पासवर्ड पुष्टि करें",
    updatePassword: "पासवर्ड अपडेट करें",
    cancel: "रद्द करें",
    passwordUpdated: "पासवर्ड अपडेट किया गया",
    passwordUpdatedDescription: "आपका पासवर्ड सफलतापूर्वक बदल दिया गया है।",
    
    // Cookie Banner
    cookieBannerTitle: "हम कुकीज़ का उपयोग करते हैं",
    cookieBannerDescription: "हम साइट कार्यक्षमता के लिए आवश्यक कुकीज़ और आपके अनुभव में सुधार के लिए विश्लेषणात्मक कुकीज़ का उपयोग करते हैं। आप अपनी प्राथमिकताएं अनुकूलित कर सकते हैं।",
    cookieAcceptAll: "सभी स्वीकार करें",
    cookieRejectAll: "सभी अस्वीकार करें",
    cookieSettings: "सेटिंग्स",
    cookieNecessary: "आवश्यक कुकीज़",
    cookieNecessaryDescription: "ये कुकीज़ वेबसाइट के सही कामकाज के लिए आवश्यक हैं। इन्हें अक्षम नहीं किया जा सकता है।",
    cookieAnalytics: "विश्लेषणात्मक कुकीज़",
    cookieAnalyticsDescription: "ये कुकीज़ हमें गुमनाम रूप से जानकारी एकत्र करके और रिपोर्टिंग करके समझने में मदद करती हैं कि आगंतुक हमारी वेबसाइट के साथ कैसे बातचीत करते हैं।",
    cookieSettingsTitle: "कुकी सेटिंग्स",
    cookieSettingsDescription: "अपनी कुकी प्राथमिकताएं अनुकूलित करें। आप नीचे विभिन्न प्रकार की कुकीज़ को सक्षम या अक्षम कर सकते हैं।",
    cookieSavePreferences: "प्राथमिकताएं सहेजें",
    
    // Sub-header banner
    bannerBadge: "सबसे क्रांतिकारी प्लेटफॉर्म",
    bannerTitle: "Market Signals24",
    bannerDescription: "ट्रिपल वैलिडेशन वाला पहला सिग्नल प्लेटफॉर्म: आर्टिफिशियल इंटेलिजेंस + मानव विशेषज्ञ + बाजार पुष्टि। झूठे सिग्नलों के लिए शून्य सहनशीलता।",
    bannerCta: "अभी खोजें",
    
    // Above-footer promo
    promoTitle: "ट्रेडर्स Market Signals24 क्यों चुनते हैं?",
    promoSubtitle: "हजारों ट्रेडर्स से जुड़ें जो पहले से हमारे ट्रिपल-वैलिडेटेड सिग्नल से लाभ कमा रहे हैं",
    promoStat1Title: "ट्रिपल वैलिडेशन",
    promoStat1Desc: "हर सिग्नल आपके पास पहुंचने से पहले AI, विशेषज्ञ ट्रेडर्स और बाजार पुष्टि से गुजरता है",
    promoStat2Title: "97.2% सटीकता",
    promoStat2Desc: "हमारा AI झूठे सिग्नल हटाता है — केवल सबसे विश्वसनीय अवसर आपकी स्क्रीन तक पहुंचते हैं",
    promoStat3Title: "24/7 रियल-टाइम",
    promoStat3Desc: "कभी कोई अवसर न चूकें — हमारा सिस्टम आपके लिए चौबीसों घंटे बाजारों की निगरानी करता है",
    promoCta: "आज ही स्मार्ट ट्रेडिंग शुरू करें",
    promoUrgency: "सीमित स्थान उपलब्ध — प्रीमियम एक्सेस जल्द बंद हो सकता है",
    
    // Popup
    popupTitle: "अंधेरे में ट्रेड न करें!",
    popupSubtitle: "93% ट्रेडर्स अनवेरिफाइड सिग्नल का उपयोग करके पैसे खो देते हैं।",
    popupHighlight: "Market Signals24 एकमात्र प्लेटफॉर्म है जो आपको भेजने से पहले हर सिग्नल को ट्रिपल-वैलिडेट करता है।",
    popupBullet1: "AI प्रति सेकंड 10,000+ डेटा पॉइंट्स का विश्लेषण करता है",
    popupBullet2: "विशेषज्ञ ट्रेडर्स हर सिग्नल को मैन्युअल रूप से कन्फर्म करते हैं",
    popupBullet3: "बाजार की स्थिति रियल-टाइम में सत्यापित होती है",
    popupCta: "अभी सत्यापित सिग्नल प्राप्त करें",
    popupDismiss: "मैं बिना सत्यापन के ट्रेडिंग का जोखिम लूंगा"
  }
};

// Fonction pour détecter la langue du navigateur
export const detectBrowserLanguage = (): string => {
  if (typeof window === 'undefined') return 'en';
  
  const browserLang = navigator.language || navigator.languages?.[0] || 'en';
  const langCode = browserLang.split('-')[0];
  
  // Vérifier si la langue est supportée
  const isSupported = supportedLanguages.some(lang => lang.code === langCode);
  return isSupported ? langCode : 'en';
};

// Fonction pour obtenir les traductions
export const getTranslations = (language: string) => {
  return globalTranslations[language as keyof typeof globalTranslations] || globalTranslations.en;
};