// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taadbjuelxonszosfrsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhYWRianVlbHhvbnN6b3NmcnNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNjM5MzYsImV4cCI6MjA2OTgzOTkzNn0.Z9Z_FFde9j9ajGD7tPWPh5tqQCf16Yp_5yigccg_HGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});